spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev 
  application:
    name: microservicecloud-config-atguigu-dev
---
spring:
  proviles:test
  application:
    name: microservicecloud-config-atguigu-test